use_frameworks!

platform :ios, '8.0'

target 'TZZPaySDK_Example' do
  pod 'TZZPaySDK', :path => '../'

  target 'TZZPaySDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
